fixed the conky bug in picom, updated init.vim && updated some bin scripts.

diff --git a/.local/bin/personal/auto_executable_permissions b/.local/bin/personal/auto_executable_permissions
--- a/.local/bin/personal/auto_executable_permissions
+++ b/.local/bin/personal/auto_executable_permissions
@@ -1,4 +1,18 @@
-#!/bin/sh
+#!/usr/bin/env bash
+#
+# Script name: auto_executable_permissions
+# Version: 1.0
+# Description: A script to set executable permissions to all the necessary scripts.
+# Dependencies: chmod
+# Github: https://github.com/Ninja-Yubaraj/Dotfiles
+# Gitlab: https://gitlab.com/Ninja-Yubaraj/Dotfiles
+# License:
+# Contributors: Yubaraj Sarkar
+
+# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
+# if certain things happen, which is a good thing.  Otherwise, we can
+# get hidden bugs that are hard to discover.
+set -euo pipefail
 
 # directories
 chmod +x $HOME/.local/bin/personal/*
diff --git a/.local/bin/personal/vbox_fixdisplay b/.local/bin/personal/vbox_fixdisplay
--- a/.local/bin/personal/vbox_fixdisplay
+++ b/.local/bin/personal/vbox_fixdisplay
@@ -1,6 +1,18 @@
-#!/bin/sh
+#!/usr/bin/env bash
 #
+# Script name: vbox_fixdisplay
+# Version: 1.0
+# Description: A script to fix the display resolution issue in VirtualBox.
 # Dependencies: xrandr
+# Github: https://github.com/Ninja-Yubaraj/Dotfiles
+# Gitlab: https://gitlab.com/Ninja-Yubaraj/Dotfiles
+# License:
+# Contributors: Yubaraj Sarkar
+
+# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
+# if certain things happen, which is a good thing.  Otherwise, we can
+# get hidden bugs that are hard to discover.
+set -euo pipefail
 
 # Easy and Quick Fix:
 xrandr --output Virtual1 --mode 1920x1080
